name: New Environment
values:
  - key: recruiterToken
    value: ''
  - key: candidateToken
    value: ''
  - key: token
    value: ''
  - key: rtoken
    value: ''
  - key: Token
    value: ''
  - key: Recruiter Token
    value: ''
  - key: rid
    value: ''
  - key: cid
    value: ''
  - key: Can
    value: ''
  - key: RecentCToken
    value: ''
  - key: RecentRToken
    value: ''
  - key: jobId
    value: ''
  - key: applicantId
    value: ''
